import type { PoolClient } from "pg";
import type { UserId } from "../../_kernel/brandedIds.ts";
import type { ContentRestriction, Flag, FlagClaim, ModerationDecision } from "./moderation.entities.ts";
import type { ContentRestrictionScope, ContentRestrictionType, FlagReasonCode, ModerationAction, ModerationSubjectType } from "./moderation.types.ts";
export const FLAGS_PORT = Symbol("FLAGS_PORT"); export const FLAG_CLAIMS_PORT = Symbol("FLAG_CLAIMS_PORT"); export const MODERATION_DECISIONS_PORT = Symbol("MODERATION_DECISIONS_PORT"); export const CONTENT_RESTRICTIONS_PORT = Symbol("CONTENT_RESTRICTIONS_PORT");
export interface FlagsPort { createIdempotent(tx: PoolClient, input: { subjectType: ModerationSubjectType; subjectId: string; reporterId: UserId; reasonCode: FlagReasonCode; reasonText: string | null; subjectSnapshot: Record<string, unknown>; priority: number; dueAt: Date; idempotencyKey: string; evidence: readonly { url: string; storageKey?: string }[] }): Promise<{ flag: Flag; created: boolean }>; findByIdForUpdate(tx: PoolClient, flagId: string): Promise<Flag | null>; listQueue(input: { status?: readonly ("open" | "assigned")[]; limit: number; cursor?: string }): Promise<{ items: ReadonlyArray<Flag & { evidence: readonly import("./moderation.entities.ts").FlagEvidence[]; claim: Pick<FlagClaim, "id" | "moderatorId" | "claimedAt" | "expiresAt"> | null; }>; nextCursor: string | null }>; markAssigned(tx: PoolClient, flagId: string): Promise<void>; markResolved(tx: PoolClient, flagId: string, status: "resolved" | "dismissed" | "open", actorId: UserId): Promise<void>; countOpen(subjectType: ModerationSubjectType, subjectId: string): Promise<number>; }
export interface FlagClaimsPort { expireActiveForFlag(tx: PoolClient, flagId: string, now: Date): Promise<void>; findActiveForFlagForUpdate(tx: PoolClient, flagId: string): Promise<FlagClaim | null>; create(tx: PoolClient, input: { flagId: string; moderatorId: UserId; expiresAt: Date }): Promise<FlagClaim>; release(tx: PoolClient, input: { claimId: string; actorId: UserId; reason: string }): Promise<boolean>; }
export interface ModerationDecisionsPort { createIdempotent(tx: PoolClient, input: Omit<ModerationDecision, "id" | "createdAt" | "reversedAt" | "reversedBy" | "reversalReason">): Promise<{ decision: ModerationDecision; created: boolean }>; findByIdForUpdate(tx: PoolClient, decisionId: string): Promise<ModerationDecision | null>; reverse(tx: PoolClient, input: { decisionId: string; actorId: UserId; reason: string }): Promise<ModerationDecision | null>; }
export interface ContentRestrictionsPort { createIdempotent(tx: PoolClient, input: Omit<ContentRestriction, "id" | "createdAt" | "liftedAt" | "liftedBy"> & { idempotencyKey: string }): Promise<{ restriction: ContentRestriction; created: boolean }>; findActiveBySubject(subjectType: ModerationSubjectType, subjectId: string): Promise<readonly ContentRestriction[]>; findActiveBySubjectForUpdate(tx: PoolClient, subjectType: ModerationSubjectType, subjectId: string): Promise<readonly ContentRestriction[]>; lift(tx: PoolClient, input: { restrictionId: string; actorId: UserId; reason: string }): Promise<ContentRestriction | null>; }
