import { ConflictException, Inject, Injectable } from "@nestjs/common";
import type { Pool, PoolClient } from "pg";
import { DATABASE_POOL } from "../../../nest/database/database.constants.ts";
import { UserId } from "../../_kernel/brandedIds.ts";
import type { Flag, FlagClaim, FlagEvidence } from "../domain/moderation.entities.ts";
import type { FlagsPort } from "../domain/moderation.ports.ts";
import type { ModerationSubjectType } from "../domain/moderation.types.ts";
type FlagRow = { id: string; subject_type: ModerationSubjectType; subject_id: string; reporter_id: string; reason_code: Flag["reasonCode"]; reason_text: string | null; subject_snapshot: Record<string, unknown>; priority: number; status: Flag["status"]; due_at: string | Date; idempotency_key: string | null; created_at: string | Date; updated_at: string | Date; closed_at: string | Date | null; closed_by: string | null };
type QueueRow = FlagRow & { evidence: { id: string; url: string; storage_key: string | null; uploaded_at: string | Date }[]; claim: { id: string; moderator_id: string; claimed_at: string | Date; expires_at: string | Date } | null };
function map(row: FlagRow): Flag { return { id: row.id, subjectType: row.subject_type, subjectId: row.subject_id, reporterId: UserId(row.reporter_id), reasonCode: row.reason_code, reasonText: row.reason_text, subjectSnapshot: row.subject_snapshot, priority: row.priority, status: row.status, dueAt: new Date(row.due_at), idempotencyKey: row.idempotency_key, createdAt: new Date(row.created_at), updatedAt: new Date(row.updated_at), closedAt: row.closed_at ? new Date(row.closed_at) : null, closedBy: row.closed_by ? UserId(row.closed_by) : null }; }
@Injectable() export class FlagsRepository implements FlagsPort { constructor(@Inject(DATABASE_POOL) private readonly pool: Pool) {}
 async countOpen(subjectType: ModerationSubjectType, subjectId: string): Promise<number> { const r=await this.pool.query<{count:string}>(`select count(*) as count from reports where subject_type=$1 and subject_id=$2 and status in ('open','assigned')`,[subjectType,subjectId]); return Number(r.rows[0]?.count??0); }
 async createIdempotent(tx: PoolClient, input: Parameters<FlagsPort["createIdempotent"]>[1]): Promise<{flag:Flag;created:boolean}> { try { const r=await tx.query<FlagRow>(`insert into reports (subject_type,subject_id,reporter_id,reason_code,reason_text,subject_snapshot,priority,due_at,idempotency_key,status,created_at,updated_at) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,'open',now(),now()) on conflict (idempotency_key) where idempotency_key is not null do nothing returning *`,[input.subjectType,input.subjectId,input.reporterId,input.reasonCode,input.reasonText,JSON.stringify(input.subjectSnapshot),input.priority,input.dueAt,input.idempotencyKey]); const row=r.rows[0]??(await tx.query<FlagRow>(`select * from reports where idempotency_key=$1`,[input.idempotencyKey])).rows[0]; if(!row) throw new Error("flag insert failed"); if(r.rows[0] && input.evidence.length > 0) for(const evidence of input.evidence) await tx.query(`insert into flag_evidence(flag_id,url,storage_key,uploaded_by) values($1,$2,$3,$4)`,[row.id,evidence.url,evidence.storageKey??null,input.reporterId]); return {flag:map(row),created:r.rows.length===1}; } catch (error: unknown) { if ((error as { code?: string }).code === "23505") throw new ConflictException("open flag already exists"); throw error; } }
 async findByIdForUpdate(tx:PoolClient,id:string):Promise<Flag|null>{const r=await tx.query<FlagRow>(`select * from reports where id=$1 for update`,[id]);return r.rows[0]?map(r.rows[0]):null;}
 async listQueue(input: Parameters<FlagsPort["listQueue"]>[0]): Promise<Awaited<ReturnType<FlagsPort["listQueue"]>>> { const result = await this.pool.query<QueueRow>(`select r.id, r.subject_type, r.subject_id, r.reporter_id, r.reason_code, r.reason_text, r.subject_snapshot, r.priority, r.status, r.due_at, r.idempotency_key, r.created_at, r.updated_at, r.closed_at, r.closed_by, coalesce(json_agg(json_build_object('id', fe.id, 'url', fe.url, 'storage_key', fe.storage_key, 'uploaded_at', fe.uploaded_at) order by fe.uploaded_at asc) filter (where fe.id is not null), '[]'::json) as evidence, case when fc.id is not null then json_build_object('id', fc.id, 'moderator_id', fc.moderator_id, 'claimed_at', fc.claimed_at, 'expires_at', fc.expires_at) else null end as claim from reports r left join flag_evidence fe on fe.flag_id = r.id left join flag_claims fc on fc.flag_id = r.id and fc.state = 'active' where r.status = any($1::text[]) and ($2::uuid is null or (r.priority < (select priority from reports where id = $2) or (r.priority = (select priority from reports where id = $2) and r.due_at > (select due_at from reports where id = $2)) or (r.priority = (select priority from reports where id = $2) and r.due_at = (select due_at from reports where id = $2) and r.id > $2))) group by r.id, fc.id, fc.moderator_id, fc.claimed_at, fc.expires_at order by r.priority desc, r.due_at asc, r.id asc limit $3`, [input.status ?? ["open", "assigned"], input.cursor ?? null, input.limit]); const items = result.rows.map(row => ({ ...map(row), evidence: (row.evidence ?? []).map((e): FlagEvidence => ({ id: e.id, flagId: String(row.id), url: e.url, storageKey: e.storage_key ?? null, uploadedBy: null, uploadedAt: new Date(e.uploaded_at) })), claim: row.claim ? { id: row.claim.id, moderatorId: UserId(row.claim.moderator_id), claimedAt: new Date(row.claim.claimed_at), expiresAt: new Date(row.claim.expires_at) } satisfies Pick<FlagClaim, "id" | "moderatorId" | "claimedAt" | "expiresAt"> : null })); return { items, nextCursor: items.length === input.limit ? items[items.length - 1]!.id : null }; }
 async markAssigned(tx:PoolClient,id:string):Promise<void>{await tx.query(`update reports set status='assigned',updated_at=now() where id=$1`,[id]);}
 async markResolved(tx:PoolClient,id:string,status:"resolved"|"dismissed"|"open",actor:ReturnType<typeof UserId>):Promise<void>{await tx.query(`update reports set status=$2,closed_at=case when $2='open' then null else now() end,closed_by=case when $2='open' then null else $3::uuid end,updated_at=now() where id=$1`,[id,status,actor]);}
}
