import { ConflictException, ForbiddenException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import { randomUUID } from "node:crypto";
import type { Pool } from "pg";
import { DATABASE_POOL } from "../../../nest/database/database.constants.ts";
import { AUDIT_LOG_PORT, type AuditLogPort } from "../../audit/public/index.ts";
import type { UserId } from "../../_kernel/brandedIds.ts";
import { SANCTIONS_TRANSACTION_PORT, type Sanction, type SanctionsTransactionPort } from "../../sanctions/public/index.ts";
import type { ContentRestriction, Flag, FlagClaim, ModerationDecision } from "../domain/moderation.entities.ts";
import { CONTENT_RESTRICTIONS_PORT, FLAG_CLAIMS_PORT, FLAGS_PORT, MODERATION_DECISIONS_PORT, type ContentRestrictionsPort, type FlagClaimsPort, type FlagsPort, type ModerationDecisionsPort } from "../domain/moderation.ports.ts";
import { computePriority } from "../domain/moderation-priority.ts";
import { computeDueAt } from "../domain/moderation-sla.ts";
import type { ContentRestrictionScope, ContentRestrictionType, FlagReasonCode, ModerationAction, ModerationSubjectType } from "../domain/moderation.types.ts";
@Injectable() export class ModerationService { constructor(@Inject(DATABASE_POOL) private readonly pool:Pool,@Inject(FLAGS_PORT) private readonly flags:FlagsPort,@Inject(FLAG_CLAIMS_PORT) private readonly claims:FlagClaimsPort,@Inject(MODERATION_DECISIONS_PORT) private readonly decisions:ModerationDecisionsPort,@Inject(CONTENT_RESTRICTIONS_PORT) private readonly restrictions:ContentRestrictionsPort,@Inject(AUDIT_LOG_PORT) private readonly audit:AuditLogPort,@Inject(SANCTIONS_TRANSACTION_PORT) private readonly sanctionsPort:SanctionsTransactionPort) {}
 private event(actor:UserId,action:"flag.submitted"|"flag.claimed"|"flag.claim_released"|"flag.decided"|"flag.decision_reversed"|"content.restricted"|"content.restriction_lifted",subject:string,after:Record<string,unknown>){return{schema_version:1 as const,id:randomUUID(),actor_user_id:actor,actor_type:"user" as const,subject_type:"flag",subject_id:subject,action,before_state:null,after_state:after,reason:null,correlation_id:randomUUID(),causation_id:null,idempotency_key:`${action}:${subject}:${randomUUID()}`,occurred_at:new Date(),legal_hold:false};}
 async submitFlag(i:{reporterId:UserId;subjectType:ModerationSubjectType;subjectId:string;reasonCode:FlagReasonCode;reasonText:string|null;subjectSnapshot:Record<string,unknown>;evidence:readonly{url:string}[];idempotencyKey:string}):Promise<{flag:Flag;created:boolean}>{const count=await this.flags.countOpen(i.subjectType,i.subjectId);const tx=await this.pool.connect();try{await tx.query("begin");const result=await this.flags.createIdempotent(tx,{...i,priority:computePriority({reasonCode:i.reasonCode,subjectType:i.subjectType,openReportCount:count,ageHours:0}),dueAt:computeDueAt(i.reasonCode,new Date()),evidence:i.evidence});if(result.created)await this.audit.record(this.event(i.reporterId,"flag.submitted",result.flag.id,{flagId:result.flag.id,subjectType:i.subjectType}),tx);await tx.query("commit");return result;}catch(e){await tx.query("rollback");throw e;}finally{tx.release();}}
 async claimFlag(i:{flagId:string;moderatorId:UserId;idempotencyKey:string}):Promise<{claim:FlagClaim;flag:Flag}>{const tx=await this.pool.connect();try{await tx.query("begin");const flag=await this.flags.findByIdForUpdate(tx,i.flagId);if(!flag)throw new NotFoundException();if(flag.status!=="open"&&flag.status!=="assigned")throw new ConflictException();await this.claims.expireActiveForFlag(tx,i.flagId,new Date());const existing=await this.claims.findActiveForFlagForUpdate(tx,i.flagId);if(existing&&existing.moderatorId!==i.moderatorId)throw new ConflictException();const claim=existing??await this.claims.create(tx,{flagId:i.flagId,moderatorId:i.moderatorId,expiresAt:new Date(Date.now()+30*60*1000)});await this.flags.markAssigned(tx,i.flagId);await this.audit.record(this.event(i.moderatorId,"flag.claimed",i.flagId,{moderatorId:i.moderatorId,expiresAt:claim.expiresAt.toISOString()}),tx);await tx.query("commit");return{claim,flag:{...flag,status:"assigned"}};}catch(e){await tx.query("rollback");throw e;}finally{tx.release();}}
 async releaseFlag(i:{flagId:string;moderatorId:UserId}):Promise<void>{const tx=await this.pool.connect();try{await tx.query("begin");const flag=await this.flags.findByIdForUpdate(tx,i.flagId);if(!flag)throw new NotFoundException();if(flag.status==="resolved"||flag.status==="dismissed")throw new ConflictException();const claim=await this.claims.findActiveForFlagForUpdate(tx,i.flagId);if(!claim)throw new NotFoundException();if(claim.moderatorId!==i.moderatorId)throw new ForbiddenException();if(!await this.claims.release(tx,{claimId:claim.id,actorId:i.moderatorId,reason:"manual"}))throw new ConflictException();await this.audit.record(this.event(i.moderatorId,"flag.claim_released",i.flagId,{claimId:claim.id}),tx);await tx.query("commit");}catch(e){await tx.query("rollback");throw e;}finally{tx.release();}}
 async decideFlag(i:{flagId:string;moderatorId:UserId;action:ModerationAction;reasonCode:FlagReasonCode;reasonNote:string|null;restriction?:{type:ContentRestrictionType;scope:ContentRestrictionScope;endsAt:Date|null};sanction?:{targetUserId:string;type:"suspension"|"ban";reasonCode:string;reasonNote?:string|null;evidenceUrl?:string|null;endsAt?:Date|null};idempotencyKey:string}):Promise<{decision:ModerationDecision;restriction:ContentRestriction|null;sanction:Sanction|null}>{const tx=await this.pool.connect();try{await tx.query("begin");const flag=await this.flags.findByIdForUpdate(tx,i.flagId);if(!flag)throw new NotFoundException();await this.claims.expireActiveForFlag(tx,i.flagId,new Date());const claim=await this.claims.findActiveForFlagForUpdate(tx,i.flagId);if(claim&&claim.moderatorId!==i.moderatorId)throw new ConflictException();let restriction:null|ContentRestriction=null;if(i.restriction)restriction=(await this.restrictions.createIdempotent(tx,{subjectType:flag.subjectType,subjectId:flag.subjectId,restrictionType:i.restriction.type,scope:i.restriction.scope,startedBy:i.moderatorId,startsAt:new Date(),endsAt:i.restriction.endsAt,idempotencyKey:`${i.idempotencyKey}:restriction`})).restriction;let sanction:Sanction|null=null;if(i.sanction){const {createHash}=await import("node:crypto");const payloadHash=createHash("sha256").update(JSON.stringify({targetUserId:i.sanction.targetUserId,type:i.sanction.type,reasonCode:i.sanction.reasonCode,endsAt:i.sanction.endsAt})).digest();sanction=await this.sanctionsPort.createInTransaction(tx,{actorId:i.moderatorId,targetUserId:i.sanction.targetUserId,type:i.sanction.type,reasonCode:i.sanction.reasonCode,reasonNote:i.sanction.reasonNote??null,evidenceUrl:i.sanction.evidenceUrl??null,endsAt:i.sanction.endsAt??null,idempotencyKey:`decision:${i.idempotencyKey}:sanction`,idempotencyPayloadHash:payloadHash});}const result=await this.decisions.createIdempotent(tx,{flagId:i.flagId,moderatorId:i.moderatorId,action:i.action,reasonCode:i.reasonCode,reasonNote:i.reasonNote,linkedRestrictionId:restriction?.id??null,linkedSanctionId:sanction?.id??null,idempotencyKey:i.idempotencyKey});await this.flags.markResolved(tx,i.flagId,i.action==="dismiss"?"dismissed":"resolved",i.moderatorId);if(result.created)await this.audit.record(this.event(i.moderatorId,"flag.decided",i.flagId,{decisionId:result.decision.id,action:i.action}),tx);await tx.query("commit");return{decision:result.decision,restriction,sanction};}catch(e){await tx.query("rollback");throw e;}finally{tx.release();}}
 async reverseDecision(i:{decisionId:string;actorId:UserId;reason:string;idempotencyKey:string}):Promise<ModerationDecision>{const tx=await this.pool.connect();try{await tx.query("begin");const d=await this.decisions.findByIdForUpdate(tx,i.decisionId);if(!d)throw new NotFoundException();if(d.reversedAt){await tx.query("commit");return d;}if(d.linkedRestrictionId){await this.restrictions.lift(tx,{restrictionId:d.linkedRestrictionId,actorId:i.actorId,reason:i.reason});}if(d.linkedSanctionId){await this.sanctionsPort.cancelInTransaction(tx,{sanctionId:d.linkedSanctionId,cancelledBy:i.actorId,cancelReason:i.reason});}const reversed=await this.decisions.reverse(tx,{decisionId:i.decisionId,actorId:i.actorId,reason:i.reason});if(!reversed)throw new ConflictException();await this.flags.markResolved(tx,d.flagId,"open",i.actorId);await this.audit.record(this.event(i.actorId,"flag.decision_reversed",d.flagId,{decisionId:d.id}),tx);await tx.query("commit");return reversed;}catch(e){await tx.query("rollback");throw e;}finally{tx.release();}}
 async getActiveRestrictions(i:{subjectType:ModerationSubjectType;subjectId:string}):Promise<readonly ContentRestriction[]>{return this.restrictions.findActiveBySubject(i.subjectType,i.subjectId);} async listQueue(input:Parameters<FlagsPort["listQueue"]>[0]):Promise<Awaited<ReturnType<FlagsPort["listQueue"]>>>{return this.flags.listQueue(input);} async getUserRestrictions(userId:string):Promise<{restrictions:Array<{action:string;remaining:number;reset_at:string|null}>}>{const sanction=await this.sanctionsPort.findActiveSanctionForUser(userId);if(!sanction)return{restrictions:[]};return{restrictions:[{action:"all_writes",remaining:0,reset_at:sanction.type==="suspension"&&sanction.endsAt?sanction.endsAt.toISOString():null}]};} }
