import { BadRequestException, Body, Controller, Delete, ForbiddenException, Get, Headers, HttpCode, Inject, Param, Post, Query, Req } from "@nestjs/common";
import { SESSION_USER, type RequestWithSession } from "../../../nest/auth/session-verifier.ts";
import { UserId } from "../../_kernel/brandedIds.ts";
import { Permissions, PermissionsService } from "../../permissions/public/index.ts";
import { ModerationService } from "../application/moderation.service.ts";
import { DecideFlagDto, ReversalDto, SubmitFlagDto } from "./moderation.dto.ts";
function actor(request:RequestWithSession){const user=request[SESSION_USER];if(!user)throw new ForbiddenException();return UserId(user.id);} function key(value:string|undefined){if(!value)throw new BadRequestException("Idempotency-Key is required");return value;}
@Controller("v1/community") export class ModerationController { constructor(@Inject(ModerationService) private readonly service:ModerationService,@Inject(PermissionsService) private readonly permissions:PermissionsService) {} private async allowed(user:ReturnType<typeof UserId>,permission:Permissions){if(!await this.permissions.hasPermission(user,permission))throw new ForbiddenException();}
 @Post("flags") @HttpCode(201) async submitFlag(@Req() request:RequestWithSession,@Body() dto:SubmitFlagDto,@Headers("idempotency-key") idempotencyKey:string){const user=actor(request);return this.service.submitFlag({reporterId:user,subjectType:dto.target.type as never,subjectId:dto.target.id,reasonCode:dto.reason_code as never,reasonText:dto.reason_text??null,subjectSnapshot:{schema_version:1},evidence:dto.evidence??[],idempotencyKey:key(idempotencyKey)});}
 @Get("moderation/queue") async queue(@Req() request:RequestWithSession,@Query("status") status?:"open"|"assigned",@Query("limit") limit?:string,@Query("cursor") cursor?:string){await this.allowed(actor(request),Permissions.MODERATION_VIEW_REPORTS);const result=await this.service.listQueue({status:status?[status]:["open","assigned"],limit:Math.min(100,Math.max(1,Number(limit) || 20)),cursor});return{items:result.items.map(item=>({id:item.id,status:item.status,priority:item.priority,due_at:item.dueAt,subject:{type:item.subjectType,id:item.subjectId,snapshot:item.subjectSnapshot},reason_code:item.reasonCode,evidence:item.evidence.map(e=>({id:e.id,url:e.url,uploaded_at:e.uploadedAt})),claim:item.claim?{id:item.claim.id,moderator_id:item.claim.moderatorId,claimed_at:item.claim.claimedAt,expires_at:item.claim.expiresAt}:null})),next_cursor:result.nextCursor};}
 @Post("flags/:id/claim") @HttpCode(201) async claim(@Req() request:RequestWithSession,@Param("id") id:string,@Headers("idempotency-key") idempotencyKey:string){const user=actor(request);await this.allowed(user,Permissions.MODERATION_RESOLVE_REPORT);return this.service.claimFlag({flagId:id,moderatorId:user,idempotencyKey:key(idempotencyKey)});}
 @Delete("flags/:id/claim") @HttpCode(204) async release(@Req() request:RequestWithSession,@Param("id") id:string){const user=actor(request);await this.allowed(user,Permissions.MODERATION_RESOLVE_REPORT);await this.service.releaseFlag({flagId:id,moderatorId:user});}
 @Post("flags/:id/decision") @HttpCode(201) async decide(@Req() request:RequestWithSession,@Param("id") id:string,@Body() dto:DecideFlagDto,@Headers("idempotency-key") idempotencyKey:string){const user=actor(request);await this.allowed(user,Permissions.MODERATION_RESOLVE_REPORT);if(dto.action==="delete"||dto.action==="restrict")await this.allowed(user,Permissions.MODERATION_DELETE_CONTENT);if(dto.sanction)await this.allowed(user,Permissions.MODERATION_MANAGE_SANCTIONS);return this.service.decideFlag({flagId:id,moderatorId:user,action:dto.action as never,reasonCode:dto.reason_code as never,reasonNote:dto.reason_note??null,restriction:dto.restriction?{type:dto.restriction.type as never,scope:dto.restriction.scope as never,endsAt:dto.restriction.ends_at?new Date(dto.restriction.ends_at):null}:undefined,sanction:dto.sanction?{targetUserId:dto.sanction.target_user_id,type:dto.sanction.type as "suspension"|"ban",reasonCode:dto.sanction.reason_code,reasonNote:dto.sanction.reason_note??null,evidenceUrl:dto.sanction.evidence_url??null,endsAt:dto.sanction.ends_at?new Date(dto.sanction.ends_at):null}:undefined,idempotencyKey:key(idempotencyKey)});}
 @Post("moderation/actions/:id/reversal") async reverse(@Req() request:RequestWithSession,@Param("id") id:string,@Body() dto:ReversalDto,@Headers("idempotency-key") idempotencyKey:string){const user=actor(request);await this.allowed(user,Permissions.MODERATION_RESOLVE_REPORT);return this.service.reverseDecision({decisionId:id,actorId:user,reason:dto.reason,idempotencyKey:key(idempotencyKey)});}
 @Get("restrictions") async restrictions(@Req() request:RequestWithSession){const user=actor(request);return this.service.getUserRestrictions(user);}
}
